### ISSUE TITLE
Not working on my theme port

### ISSUE THREAD

**Issue by plttn** [braver/selection-outlines#3]
What style selector do I need to add to mine to get it to work (http://github.com/plttn/tubster-syntax)?

It works on other themes, so I'm not sure what I didn't add to this port to get it working.

![2015-02-15_21-36-31](https://cloud.githubusercontent.com/assets/7369280/6207592/c074904e-b55a-11e4-8138-fa3743e6bde4.png)

**Comment by braver** [comment]
It does seem to activate, but the outline isn't very visible. This is due to the theme using a semi-transparent selection color. If you want the outlines to work well, you need to use a solid color. There should also be no need to use a semi-transparent selection color, since the background will always be the same.
